version: "2"
services:
  hub:
    image: selenium/hub
    ports:
      - 4444:4444
    networks:
      - gridify_default
  chrome:
    image: selenium/node-chrome
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    networks:
      - gridify_default
networks:
  gridify_default: